#!/usr/bin/env python3
"""Print the current state of study. Run this first in any new session.

Reads plan.yml, progress.yml, exams/attempts/*.yml and the question bank.
Derives everything -- nothing here is a stored snapshot that can go stale.

    python3 status.py
"""
import datetime
import glob
import os
import sys
from collections import Counter

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))
CUT = 65


def rel(p):
    return os.path.join(ROOT, p)


def load_plan():
    """The plan is per-person and generated by the onboarding skill, so a fresh
    clone has none. Everything below degrades to 'no plan yet' instead of failing."""
    path = rel("plan.yml")
    if not os.path.isfile(path):
        return None
    try:
        plan = yaml.safe_load(open(path)) or {}
        plan["phases"] = plan.get("phases") or []
        for p in plan["phases"]:
            lo, hi = p["days"]
            int(lo), int(hi)
    except Exception as e:
        # Hand-edited file: say what broke instead of dying on a traceback.
        print(f"!! plan.yml could not be read ({type(e).__name__}: {e}).")
        print("   Fix it by hand, or re-run /onboarding to rebuild it.\n")
        return None
    return plan


def as_date(v):
    if isinstance(v, datetime.date):
        return v
    if isinstance(v, str) and v.strip():
        try:
            return datetime.date.fromisoformat(v.strip())
        except ValueError:
            return None
    return None


def bar(n, total, width=22):
    filled = 0 if not total else round(width * n / total)
    return "#" * filled + "." * (width - filled)


def main():
    if not os.path.isdir(rel("vendor/dbt-docs/website/docs")):
        print("!! vendor/dbt-docs is missing -- technical answers cannot be grounded.")
        print("   See 'Setting up a new machine' in README.md.\n")

    progress = yaml.safe_load(open(rel("progress.yml")))["subskills"]
    topics = yaml.safe_load(open(rel("exam/topics.yml")))["topics"]
    tname = {t["id"]: t["name"] for t in topics}

    questions = []
    for f in sorted(glob.glob(rel("exams/bank/*.yml"))):
        questions += yaml.safe_load(open(f))
    qcount = Counter(q["subskill"] for q in questions)

    plan = load_plan()
    today = datetime.date.today()

    print("=" * 66)
    print("  dbt Analytics Engineering Certification -- study status")
    print("=" * 66)

    phase = None
    if plan is None:
        print("  No plan yet.  Run the /onboarding skill: a short questionnaire, a")
        print("  time budget and a diagnostic, and it writes your plan.")
        print("  Everything below still works -- it just is not prioritised yet.")
    else:
        exam_date = as_date(plan.get("exam_date"))
        start = as_date(plan.get("start_date")) or today
        day_n = (today - start).days + 1
        total_days = max((p["days"][1] for p in plan["phases"]), default=0)

        if exam_date:
            left = (exam_date - today).days
            print(f"  Target exam date : {exam_date}  ({left} days away)" if left >= 0
                  else f"  Target exam date : {exam_date}  (PASSED {-left} days ago)")
        else:
            hpw = plan.get("hours_per_week")
            weeks = -(-total_days // 7) if total_days else 0
            print(f"  Target exam date : not booked yet"
                  + (f"  ({weeks}-week plan, {hpw} h/week)" if weeks else ""))

        phase = next((p for p in plan["phases"] if p["days"][0] <= day_n <= p["days"][1]), None)
        if not plan["phases"]:
            print("  Plan has no phases -- re-run /onboarding to rebuild it.")
        elif phase:
            week = -(-day_n // 7)
            where = f"day {day_n} of {total_days}" if exam_date else f"week {week}, day {day_n}"
            print(f"  Plan {where}  ->  {phase['title']}")
            if phase.get("why"):
                print(f"                          {phase['why']}")
        elif day_n < 1:
            print(f"  Plan starts {start}")
        else:
            print(f"  Plan day {day_n} -- past the {total_days}-day window in STUDY-PLAN.md")

    # ---- attempt history -------------------------------------------------
    print("\n  ATTEMPTS")
    attempts = []
    for f in sorted(glob.glob(rel("exams/attempts/*.yml"))):
        attempts.append(yaml.safe_load(open(f)))
    if not attempts:
        print("    none yet -- run a diagnostic to map your gaps")
    for a in attempts:
        lucky = sum(1 for x in a.get("answers", []) if x.get("quadrant") == "lucky")
        quads = a.get("quadrants") or Counter(x.get("quadrant") for x in a.get("answers", []))
        lucky = lucky or quads.get("lucky", 0)
        adj = round(100 * (a["score"] - lucky) / a["total"], 1)
        flag = "PASS" if a["percent"] >= CUT else "under"
        note = "  (reconstructed)" if a.get("reconstructed") else ""
        print(f"    {a['date']}  {a['mode']:<10} {a['score']:>2}/{a['total']:<3} "
              f"{a['percent']:>5}%  {flag:<5}  adjusted {adj}%{note}")
    if attempts:
        print("    adjusted = score minus lucky guesses. Plan against that number.")

    # ---- weak sub-skills -------------------------------------------------
    order = {"weak": 0, "unknown": 1, "ok": 2, "strong": 3}
    weak = sorted(
        (k for k, v in progress.items() if v["confidence"] in ("weak", "unknown")),
        key=lambda k: (order[progress[k]["confidence"]], k),
    )
    print(f"\n  NEEDS WORK  ({len(weak)} of {len(progress)} sub-skills)")
    for k in weak:
        v = progress[k]
        acc = f"{v['correct']}/{v['seen']}" if v["seen"] else "unseen"
        print(f"    {k}  {v['confidence']:<8} {acc:<8} {qcount[k]}q   {v['name'][:52]}")

    # ---- topic coverage --------------------------------------------------
    print("\n  TOPIC COVERAGE  (confidence across sub-skills)")
    for t in topics:
        subs = [s["id"] for s in t["subskills"]]
        good = sum(1 for s in subs if progress[s]["confidence"] in ("ok", "strong"))
        nq = sum(qcount[s] for s in subs)
        print(f"    {t['id']}  {bar(good, len(subs))}  {good}/{len(subs)} solid   "
              f"{nq:>2}q   {tname[t['id']][:40]}")

    print(f"\n  BANK  {len(questions)} questions")
    fmt = Counter(q["type"] for q in questions)
    print("    " + "  ".join(f"{k} {v}" for k, v in fmt.most_common()))

    # Order by the plan's current phase, not alphabetically: the phase decides
    # which topics matter now, and weak beats unknown inside that.
    focus = (phase.get("topics") or []) if phase else []
    ranked = sorted(weak, key=lambda k: (
        0 if progress[k]["topic"] in focus else 1,
        order[progress[k]["confidence"]],
        k,
    ))
    print("\n  NEXT")
    if plan is None:
        print("    1. Run /onboarding -- questionnaire, time budget, diagnostic, plan")
        print("    2. The diagnostic fills in progress.yml; the plan orders it")
    elif not weak:
        print("    1. No weak sub-skills left -- run a full 65-question mock")
    else:
        top = ranked[:3]
        why = f" (phase focus: topics {', '.join(focus)})" if focus and any(
            progress[k]["topic"] in focus for k in top) else ""
        print(f"    1. Study: {', '.join(top)}{why}")
        for k in top:
            print(f"         {k}  {progress[k]['name'][:56]}")
        print("    2. Then ask for a 'weak' drill to re-test them")
    print("    3. Every drill is graded and recorded in exams/attempts/")
    if plan is not None:
        print("\n  Read STUDY-PLAN.md for the full sequence.")
    print("=" * 66)
    return 0


if __name__ == "__main__":
    sys.exit(main())
